### ISSUE TITLE
Add new Python Questions and answers

### ISSUE THREAD

**Issue by RaviKarrii** [RaviKarrii/Awesome-interview-preparation#1]
This issue is open for ALL. Please add Interview questions and answers. 

Please keep it this repo clean.

**Comment by abxsantos** [comment]
I've been asked a lot about the fibonnacci sequence functions (iterative and recursive) during interviews. 
Can I add the question here with the solution?

**Comment by RaviKarrii** [comment]
Yes Please. Anything that would help users prepare for interviews. 

 You may also add your GitHub ID if you like. may be  say ( added by  (User))

**Comment by abxsantos** [comment]
Great! Should I add in as a markdown file, as a python file or both?

**Comment by RaviKarrii** [comment]
You can create the program in a folder named "Supporting files" in python folder. and link it in markdown file

**Comment by azhar1038** [comment]
I have added another Python interview coding question which I faced in my interview. Optimised algorithm to find Fibonacci number O(log n). I have also added program in the supporting folder. Please do check, I have sent the PR!
